# Reading, Sorting, and Normalizing EEG data with Pandas
Hi my name is James and I'm a CS student at Binghamton University.
<br>
The goal of this entire ML and BCI blog is to build a strong foundation in statistics, machine learning, and signal processing so that I can apply it to brain-computer-interface (BCI) research.

BCI's are my #1 interest so instead of rushing into state-of-the-art research and trying to learn about CNN's and other deep learning things right away (as I have tried to the past week),
<br>
I thought I should be discipline and start from the beginning.

Today I will be learning about Pandas
- I've worked with Pandas before, but it was more to use it for a piece of a project, so I never took the time to actually _learn_ it fully.
- Pandas will be crucial to the following blogs because I will be working with data for the rest of the existence of this blog.
- I plan to learn as much as I can throughout this notebook!

_Please_ email me if you have any questions or see any mistakes in either my code or commentary (jamesmcaleer717@gmail.com)

In [ ]:
pip install pandas

In [60]:
import pandas as pd

I will be inserting and plotting data from OpenBCI's sample data that comes with their GUI applications
<br>

"It's a text file, so although I use the read_csv function, I have to specify tab (\t) as the delimiter"
<br>

I am going to keep this blog transparent, this above was my thought at first but as I looked further into the data, I realized it _was_ still comma separated
<br>
I also had issues trying to show the columns due to the incorrect parsing of information due to the '%' signs as comments in the txt file
<br>
I now know to include the comment argument when reading a file

## Reading EEG Data

In [61]:
df = pd.read_csv('/Users/jmac/Programming/BCI/2025/blog/notebooks/pandas/openbci-sample.txt', delimiter=',', comment='%')

So here is the columns of the data!
<br>
Everything is stored in something called a pandas _DataFrame_ which is the object that holds this table of rows and columns

In [62]:
print(df.columns)

Index(['Sample Index', ' EXG Channel 0', ' EXG Channel 1', ' EXG Channel 2',
       ' EXG Channel 3', ' EXG Channel 4', ' EXG Channel 5', ' EXG Channel 6',
       ' EXG Channel 7', ' Accel Channel 0', ' Accel Channel 1',
       ' Accel Channel 2', ' Not Used', ' Digital Channel 0 (D11)',
       ' Digital Channel 1 (D12)', ' Digital Channel 2 (D13)',
       ' Digital Channel 3 (D17)', ' Not Used.1', ' Digital Channel 4 (D18)',
       ' Analog Channel 0', ' Analog Channel 1', ' Analog Channel 2',
       ' Timestamp', ' Marker Channel', ' Timestamp (Formatted)'],
      dtype='object')

And here is an example of one of the samples

In [63]:
print(df.head(1))

   Sample Index   EXG Channel 0   EXG Channel 1   EXG Channel 2  \
0             0        61379.36        49492.89       -16597.06

    EXG Channel 3   EXG Channel 4   EXG Channel 5   EXG Channel 6  \
0       -21309.75         6703.91        -3284.86          7223.1

    EXG Channel 7   Accel Channel 0  ...   Digital Channel 2 (D13)  \
0         1740.11              0.04  ...                         0

    Digital Channel 3 (D17)   Not Used.1   Digital Channel 4 (D18)  \
0                         0            0                         0

    Analog Channel 0   Analog Channel 1   Analog Channel 2      Timestamp  \
0                  0                  0                  0  1557936053329

    Marker Channel   Timestamp (Formatted)
0                0            12:00:53.329

[1 rows x 25 columns]

You can see as I increase the value inside of .head(), we have more samples. This is good to know

In [64]:
print(df.head(5))

   Sample Index   EXG Channel 0   EXG Channel 1   EXG Channel 2  \
0             0        61379.36        49492.89       -16597.06
1             1        60973.46        48972.47       -16279.02
2             2        61433.45        49486.27       -16245.72
3             3        61788.96        49917.57       -16488.30
4             4        61512.69        49619.42       -16606.27

    EXG Channel 3   EXG Channel 4   EXG Channel 5   EXG Channel 6  \
0       -21309.75         6703.91        -3284.86         7223.10
1       -21050.13         7045.02        -2887.53         7593.09
2       -20920.25         7035.70        -2916.12         7561.15
3       -21147.99         6770.81        -3223.32         7286.27
4       -21326.92         6676.73        -3309.31         7188.50

    EXG Channel 7   Accel Channel 0  ...   Digital Channel 2 (D13)  \
0         1740.11              0.04  ...                         0
1         2118.70              0.04  ...                         0
2         2090.85              0.04  ...                         0
3         1805.86              0.04  ...                         0
4         1709.48              0.04  ...                         0

    Digital Channel 3 (D17)   Not Used.1   Digital Channel 4 (D18)  \
0                         0            0                         0
1                         0            0                         0
2                         0            0                         0
3                         0            0                         0
4                         0            0                         0

    Analog Channel 0   Analog Channel 1   Analog Channel 2      Timestamp  \
0                  0                  0                  0  1557936053329
1                  0                  0                  0  1557936053336
2                  0                  0                  0  1557936053336
3                  0                  0                  0  1557936053343
4                  0                  0                  0  1557936053343

    Marker Channel   Timestamp (Formatted)
0                0            12:00:53.329
1                0            12:00:53.336
2                0            12:00:53.336
3                0            12:00:53.343
4                0            12:00:53.343

[5 rows x 25 columns]

## Narrowing down the data

And here are the first 20 samples from Channel 0
<br>

I've also noticed that while 'EXG' channels have data, 'Digital' channels do not, so from here on out, I will only be displaying information from 'EXG' channels

### Columns of DataFrame

In [65]:
print(df[' EXG Channel 0'][0:20])

0     61379.36
1     60973.46
2     61433.45
3     61788.96
4     61512.69
5     60988.50
6     61315.06
7     61769.25
8     61622.57
9     61061.59
10    61240.47
11    61796.87
12    61744.46
13    61160.23
14    61165.82
15    61760.48
16    61824.21
17    61294.61
18    61103.03
19    61696.47
Name:  EXG Channel 0, dtype: float64

Now to show multiple columns, we put the column names in a list. Now if you think im going to type out all 8 channels in brute-force, you don't know me yet.

In [66]:
print(df[ [' EXG Channel 0', ' EXG Channel 1'] ]) # .. and so on

       EXG Channel 0  EXG Channel 1
0           61379.36       49492.89
1           60973.46       48972.47
2           61433.45       49486.27
3           61788.96       49917.57
4           61512.69       49619.42
...              ...            ...
22485       58750.42       47034.95
22486       59029.14       47391.53
22487       58890.72       47196.80
22488       58567.63       46769.70
22489       58705.56       46972.84

[22490 rows x 2 columns]

Let's come up with a better solution...
<br>
And great, it works!

In [67]:
chans = []
for i in range(8):
    chans.append(f" EXG Channel {i}")

print(df[chans])

       EXG Channel 0  EXG Channel 1  EXG Channel 2  EXG Channel 3  \
0           61379.36       49492.89      -16597.06      -21309.75
1           60973.46       48972.47      -16279.02      -21050.13
2           61433.45       49486.27      -16245.72      -20920.25
3           61788.96       49917.57      -16488.30      -21147.99
4           61512.69       49619.42      -16606.27      -21326.92
...              ...            ...            ...            ...
22485       58750.42       47034.95      -18637.04      -27128.40
22486       59029.14       47391.53      -18737.73      -27217.09
22487       58890.72       47196.80      -18850.75      -27389.65
22488       58567.63       46769.70      -18777.12      -27361.26
22489       58705.56       46972.84      -18624.12      -27123.57

       EXG Channel 4  EXG Channel 5  EXG Channel 6  EXG Channel 7
0            6703.91       -3284.86        7223.10        1740.11
1            7045.02       -2887.53        7593.09        2118.70
2            7035.70       -2916.12        7561.15        2090.85
3            6770.81       -3223.32        7286.27        1805.86
4            6676.73       -3309.31        7188.50        1709.48
...              ...            ...            ...            ...
22485       -9182.90      -18376.35       -5918.16       -6498.79
22486       -9327.85      -18544.50       -6069.39       -6654.94
22487       -9400.32      -18621.62       -6141.32       -6739.32
22488       -9255.01      -18427.36       -5976.43       -6570.79
22489       -9153.87      -18340.03       -5887.83       -6470.99

[22490 rows x 8 columns]

### Rows of DataFrame

'iloc' allows me to get specific rows from the DataFrame

In [68]:
df.iloc[0:2]

,Sample Index,EXG Channel 0,EXG Channel 1,EXG Channel 2,EXG Channel 3,EXG Channel 4,EXG Channel 5,EXG Channel 6,EXG Channel 7,Accel Channel 0,...,Digital Channel 2 (D13),Digital Channel 3 (D17),Not Used.1,Digital Channel 4 (D18),Analog Channel 0,Analog Channel 1,Analog Channel 2,Timestamp,Marker Channel,Timestamp (Formatted)
0,0,61379.36,49492.89,-16597.06,-21309.75,6703.91,-3284.86,7223.10,1740.11,0.04,...,0,0,0,0,0,0,0,1557936053329,0,12:00:53.329
1,1,60973.46,48972.47,-16279.02,-21050.13,7045.02,-2887.53,7593.09,2118.70,0.04,...,0,0,0,0,0,0,0,1557936053336,0,12:00:53.336

Let's combine this with getting retrieving specific columns to get a chunk of the EEG data I'm looking for...

In [69]:
df[chans].iloc[0:10]

,EXG Channel 0,EXG Channel 1,EXG Channel 2,EXG Channel 3,EXG Channel 4,EXG Channel 5,EXG Channel 6,EXG Channel 7
0,61379.36,49492.89,-16597.06,-21309.75,6703.91,-3284.86,7223.10,1740.11
1,60973.46,48972.47,-16279.02,-21050.13,7045.02,-2887.53,7593.09,2118.70
2,61433.45,49486.27,-16245.72,-20920.25,7035.70,-2916.12,7561.15,2090.85
3,61788.96,49917.57,-16488.30,-21147.99,6770.81,-3223.32,7286.27,1805.86
4,61512.69,49619.42,-16606.27,-21326.92,6676.73,-3309.31,7188.50,1709.48
5,60988.50,48976.52,-16344.53,-21154.36,6952.42,-2958.16,7481.04,2029.85
6,61315.06,49330.77,-16228.46,-20954.00,7035.21,-2914.51,7554.31,2106.12
7,61769.25,49873.18,-16460.85,-21159.12,6771.26,-3225.07,7291.07,1823.68
8,61622.57,49717.79,-16574.18,-21321.87,6670.45,-3319.14,7204.59,1729.71
9,61061.59,49044.09,-16355.02,-21197.70,6914.80,-2998.60,7478.65,2022.79

Now I'm going to try a couple of options for iterating through this data, sample-by-sample

In [70]:
two_chans = chans[0:2]

for i in range(3):
    print(df[two_chans].iloc[i]) # only showing the first 2 channels and first 3 samples to save space

EXG Channel 0    61379.36
EXG Channel 1    49492.89
Name: 0, dtype: float64
EXG Channel 0    60973.46
EXG Channel 1    48972.47
Name: 1, dtype: float64
EXG Channel 0    61433.45
EXG Channel 1    49486.27
Name: 2, dtype: float64

This pre-built function I found 'iterrows()' seems to have the same effect
<br>

I don't seem to have the same control over how many rows I iterate through, and I would imagine iterrows() is faster than me calling iloc() every iteration
<br>

So from here on out, I will be using the pre-built function
<br>

If I don't want to loop through ALL samples, I simply call iloc() once on the dataframe before the loop to chop it

In [71]:
for index, row in df[two_chans].iloc[0:3].iterrows():
    print(f"Sample: {index}", row)

Sample: 0 EXG Channel 0    61379.36
EXG Channel 1    49492.89
Name: 0, dtype: float64
Sample: 1 EXG Channel 0    60973.46
EXG Channel 1    48972.47
Name: 1, dtype: float64
Sample: 2 EXG Channel 0    61433.45
EXG Channel 1    49486.27
Name: 2, dtype: float64

## Describing Data

Now that I have some control over this data, I want to start looking for peaks, averages, and more
<br>

To start with this, let's explore the 'loc()' function, not to be confused wit 'iloc()'
<br>

To my knowledge, 'loc()' lets me find parts of the DataFrame where a condition is true, similar to the 'WHERE' in SQL
<br>

I'm going to try to show rows where the amplitude is above average in Channel 0
<br>

<hr>

So something weird happened here, when I tried to call 'iterrows()' on df[' EXG Channel 0'], I had an error as I could not call the method on a Series
<br>
Instead, I have to nest the channel in another list, similar to my list 'chans' before so that the type is correct to run the method on

<hr>

Anyways, it was a success. From a programming standpoint, if you are wondering how I used 'index' for calculating my average, the last value of 'index' 
<br>
(and any other incrementing value) retains its final value and can be used outside the loop. Pretty cool

In [72]:
sum_vals = 0
for index, row in df[ [' EXG Channel 0'] ].iterrows():
    sum_vals += row[' EXG Channel 0']

avg = sum_vals / index

df.loc[df[' EXG Channel 0'] > avg][chans]

,EXG Channel 0,EXG Channel 1,EXG Channel 2,EXG Channel 3,EXG Channel 4,EXG Channel 5,EXG Channel 6,EXG Channel 7
49,62115.68,49995.62,-16410.43,-21149.15,6761.22,-3218.14,7325.83,1857.05
53,62131.95,49988.42,-16366.66,-21125.55,6796.81,-3184.70,7363.18,1905.26
57,62141.63,49966.92,-16335.53,-21079.88,6825.46,-3134.47,7412.31,1949.30
61,62087.18,49875.99,-16326.41,-21072.31,6832.50,-3141.14,7410.81,1938.68
62,62103.98,49894.99,-16482.42,-21258.61,6691.51,-3292.43,7265.05,1787.71
...,...,...,...,...,...,...,...,...
11762,62063.10,50175.29,-17061.58,-25087.46,-3624.87,-14380.49,-1304.47,-4666.73
11800,62075.04,50143.72,-17040.14,-25119.25,-3589.33,-14337.21,-1267.41,-4643.98
11804,62062.50,50147.81,-17079.24,-25141.35,-3647.04,-14393.79,-1315.40,-4686.40
11812,62064.18,50178.52,-17071.19,-25113.93,-3662.58,-14425.35,-1353.49,-4719.53
11829,62056.84,50148.71,-17090.08,-25149.33,-3677.26,-14415.58,-1349.84,-4702.76

### 'describe()' method

There is actually a built in function called 'describe()' that gives me the mean, std deviation, and more about my EEG data!

In [73]:
df[chans].describe()

,EXG Channel 0,EXG Channel 1,EXG Channel 2,EXG Channel 3,EXG Channel 4,EXG Channel 5,EXG Channel 6,EXG Channel 7
count,22490.000000,22490.000000,22490.000000,22490.000000,22490.000000,22490.000000,22490.000000,22490.000000
mean,62052.053014,49483.123424,-16894.982320,-24637.813016,-2401.919517,-12709.964997,-337.359995,-3600.225886
std,1901.172413,1217.997622,928.612881,1801.884862,4594.161796,4318.666035,3883.880608,2477.683470
min,58533.630000,46734.390000,-19600.620000,-27979.800000,-9840.470000,-19232.920000,-6256.950000,-6936.890000
25%,60282.550000,48362.010000,-17675.450000,-26214.065000,-6310.007500,-16188.677500,-3702.482500,-5638.092500
50%,61926.690000,49798.665000,-16883.000000,-24912.430000,-3174.125000,-13985.265000,-894.630000,-4371.405000
75%,63508.645000,50435.247500,-16205.927500,-23553.177500,919.175000,-10147.227500,2468.687500,-2020.805000
max,65682.840000,51689.880000,-14988.790000,-20602.380000,7344.180000,-2602.880000,7940.500000,2450.560000

If I want to _just_ get the max of each channel, I can specify that I want it

In [74]:
df[chans].describe().loc['max']

EXG Channel 0    65682.84
EXG Channel 1    51689.88
EXG Channel 2   -14988.79
EXG Channel 3   -20602.38
EXG Channel 4     7344.18
EXG Channel 5    -2602.88
EXG Channel 6     7940.50
EXG Channel 7     2450.56
Name: max, dtype: float64

Upon further research, I can also just use the 'max()' method
<br>

Let's also try to access a single channel's max (this will be helpful later)

In [75]:
df[chans].max().iloc[0]

np.float64(65682.84)

## Sorting Data

I'm not sure how necessary this will be for EEG data, but say I wanted sort all amplitudes from lowest to highest,
<br>
and find the timestamp of each.

### Sorting just by Channel 0

In [76]:
df.sort_values([' EXG Channel 0'])[chans]

,EXG Channel 0,EXG Channel 1,EXG Channel 2,EXG Channel 3,EXG Channel 4,EXG Channel 5,EXG Channel 6,EXG Channel 7
22484,58533.63,46734.68,-18746.52,-27325.14,-9229.08,-18393.54,-5960.74,-6542.96
22480,58534.25,46734.39,-18708.01,-27264.46,-9184.29,-18358.96,-5920.71,-6501.07
22476,58549.36,46769.77,-18692.92,-27235.80,-9187.39,-18350.89,-5926.48,-6503.13
22459,58567.04,46772.77,-18731.48,-27294.88,-9215.78,-18378.03,-5939.71,-6521.43
22488,58567.63,46769.70,-18777.12,-27361.26,-9255.01,-18427.36,-5976.43,-6570.79
...,...,...,...,...,...,...,...,...
1722,65675.75,51615.29,-15498.36,-21397.99,5486.62,-4544.80,6181.69,850.33
1939,65679.37,51636.89,-15487.03,-21506.69,5276.00,-4806.16,5932.29,675.31
1701,65682.41,51641.56,-15499.93,-21372.80,5501.14,-4541.94,6194.54,859.60
1676,65682.56,51636.75,-15490.41,-21353.72,5530.36,-4511.43,6219.98,876.64
1705,65682.84,51640.82,-15491.75,-21351.73,5494.21,-4549.38,6182.74,849.95

### Sorting by all channels

In [77]:
df.sort_values(chans)[chans]

,EXG Channel 0,EXG Channel 1,EXG Channel 2,EXG Channel 3,EXG Channel 4,EXG Channel 5,EXG Channel 6,EXG Channel 7
22484,58533.63,46734.68,-18746.52,-27325.14,-9229.08,-18393.54,-5960.74,-6542.96
22480,58534.25,46734.39,-18708.01,-27264.46,-9184.29,-18358.96,-5920.71,-6501.07
22476,58549.36,46769.77,-18692.92,-27235.80,-9187.39,-18350.89,-5926.48,-6503.13
22459,58567.04,46772.77,-18731.48,-27294.88,-9215.78,-18378.03,-5939.71,-6521.43
22488,58567.63,46769.70,-18777.12,-27361.26,-9255.01,-18427.36,-5976.43,-6570.79
...,...,...,...,...,...,...,...,...
1722,65675.75,51615.29,-15498.36,-21397.99,5486.62,-4544.80,6181.69,850.33
1939,65679.37,51636.89,-15487.03,-21506.69,5276.00,-4806.16,5932.29,675.31
1701,65682.41,51641.56,-15499.93,-21372.80,5501.14,-4541.94,6194.54,859.60
1676,65682.56,51636.75,-15490.41,-21353.72,5530.36,-4511.43,6219.98,876.64
1705,65682.84,51640.82,-15491.75,-21351.73,5494.21,-4549.38,6182.74,849.95

If you look closely, you will see that these two DataFrames are the exact same, I was very confused by this because while one
<br>
the first sorts the data from lowest to highest based on channel 0, the second should sort it by all channels
<br>

The reason the outputs are the same is because Pandas first sorts by Channel 0, then by Channel 1, and so on
<br>

If I reverse the list and sort, we should have a different output

### Reversing the channels

In [78]:
r_chans = chans[::-1]
df.sort_values(r_chans)[chans]

,EXG Channel 0,EXG Channel 1,EXG Channel 2,EXG Channel 3,EXG Channel 4,EXG Channel 5,EXG Channel 6,EXG Channel 7
22081,59087.04,47331.67,-19367.74,-27498.01,-9840.47,-19026.50,-6256.95,-6936.89
21564,59128.23,47276.71,-19315.95,-27675.93,-9323.61,-18468.38,-6099.68,-6857.65
22073,59072.71,47394.77,-19098.92,-27602.66,-9465.56,-18673.63,-6157.17,-6824.97
22077,59130.38,47487.04,-18725.11,-27280.21,-9234.11,-18665.14,-6095.48,-6811.87
21952,59157.09,47448.77,-18712.41,-27283.52,-9560.98,-18558.50,-6122.86,-6800.74
...,...,...,...,...,...,...,...,...
114,61808.98,49179.94,-15916.54,-20823.71,7240.98,-2680.13,7827.87,2412.94
164,62151.13,49268.85,-15752.82,-20867.63,7281.91,-2636.97,7903.02,2423.33
118,61802.01,49141.02,-15918.93,-20846.85,7253.43,-2667.88,7848.86,2424.47
122,61907.09,49191.09,-15880.58,-20820.36,7268.79,-2645.02,7876.24,2447.69
160,62297.28,49396.64,-15673.76,-20795.73,7344.18,-2602.88,7940.50,2450.56

And the hypothesis is confirmed!

## Filtering Data

Remember how we wrote this code to find the samples where the amplitude of Channel 0 was above average?

In [79]:
'''
sum_vals = 0
for index, row in df[ [' EXG Channel 0'] ].iterrows():
    sum_vals += row[' EXG Channel 0']

avg = sum_vals / index

df.loc[df[' EXG Channel 0'] > avg][chans]
'''
print()

Instead, lets now use _Filtering_ to find the samples where _all_ of the channels have an above average amplitude

In [80]:
sums = [0] * 8
for index, row in df[chans].iterrows():
    for i in range(8):
        sums[i] += row[f' EXG Channel {i}']

avgs = []
for s in sums:
    avgs.append((s / index) * 1.00) # increase this number (1.00) and to increase the cutoff

'''
above_avg = True

for i, col in enumerate(chans):
    above_avg &= df[col] > avgs[i]

#df.loc[above_avg][chans]
df.loc[above_avg, chans]
'''
print()

### Bug...
After returning to this a day later, I realize that the code above in the comments will NOT work
<br>
Let's get into it:
<br>

Since the 'loc()' method takes in conditions, I thought I would be able to AND the 8 channels WHERE their values were greater than the average.
<br>
This is why you see me looping through and using '&='. However this will not work because what we are trying to do with 'loc()' is filter the DataFrame
<br>
where certain conditions are true. Pandas has its _own_ syntax for ANDs, instead of 'and' it is '&'.
<br>

The reason for this is because the ANDs we are aiming to do don't actually fit the way an 'and' works in Python. Instead, 'loc()' narrows down the df
<br>
from the first condition, then uses its own '&' to see we should futher narrow down the df to the next condition. My above code simply creates a 
<br>
boolean variable in which we AND the current channel being greater than the average to the variable. This doesn't actually locate the rows WHERE
<br>
the values are greater.
<br>

I though I'd type out my entire thought process here to make sure I really understood the bug. In the future of this blog, I might only highlight the most
<br>
important bugs in a manner like this.

### Fixed
Sadly, until I can think of a better solution, we will have to brute force the custom '&'s that Pandas uses

In [81]:
df.loc[(df[' EXG Channel 0'] > avgs[0]) & (df[' EXG Channel 1'] > avgs[1]) & (df[' EXG Channel 2'] > avgs[2]) & (df[' EXG Channel 3'] > avgs[3]) & (df[' EXG Channel 4'] > avgs[4]) & (df[' EXG Channel 5'] > avgs[5]) & (df[' EXG Channel 6'] > avgs[6]) & (df[' EXG Channel 7'] > avgs[7])][chans]

,EXG Channel 0,EXG Channel 1,EXG Channel 2,EXG Channel 3,EXG Channel 4,EXG Channel 5,EXG Channel 6,EXG Channel 7
49,62115.68,49995.62,-16410.43,-21149.15,6761.22,-3218.14,7325.83,1857.05
53,62131.95,49988.42,-16366.66,-21125.55,6796.81,-3184.70,7363.18,1905.26
57,62141.63,49966.92,-16335.53,-21079.88,6825.46,-3134.47,7412.31,1949.30
61,62087.18,49875.99,-16326.41,-21072.31,6832.50,-3141.14,7410.81,1938.68
62,62103.98,49894.99,-16482.42,-21258.61,6691.51,-3292.43,7265.05,1787.71
...,...,...,...,...,...,...,...,...
9290,62319.43,49917.72,-16503.68,-24421.47,-1759.19,-12699.23,295.53,-3527.22
9307,62238.72,49845.33,-16472.88,-24363.65,-1742.52,-12690.58,321.71,-3503.86
9311,62294.40,49890.75,-16461.48,-24374.44,-1724.03,-12667.54,331.16,-3489.08
9315,62326.18,49906.28,-16494.16,-24429.54,-1746.81,-12702.99,318.87,-3521.05
9336,62275.47,49866.18,-16490.47,-24410.09,-1761.79,-12704.42,301.59,-3518.28

## Normalizing EEG Channels
To wrap up this blog, I want to challenge myself to normalize all of the values in the 8 channels of this DataFrame

So after some research, the formula for the normalization I want to do (min-max normalization) is, for each element of a column, 
<br>
(x_i - x_min) / (x_max - m_min). In this case, x_i is the ith element of the column.
<br>

To do this normalization there are a couple of steps I need to take:
- Find the min and max of the column
- On each iteration, locate the element at position i
- Apply the formula and put this new value in the _result_ DataFrame
- Repeat for all 8 channels

In [82]:
# df[chans].max().iloc[0] | we will be using this logic from this line created earlier in the blog
maxs = []
mins = []

df_max = df[chans].max() # make it into its own variable to save from finding the max every iteration
df_min = df[chans].min()

result = {} # this will soon be turned into a DataFrame
for i in range(8):
    maxs.append(df_max.iloc[i])
    mins.append(df_min.iloc[i])
    result[f'Channel {i}'] = []

normalized = pd.DataFrame(result)

for index, row in df[chans].iterrows(): 
    for i in range(8):
        x_i = row[f' EXG Channel {i}']
        normalized.loc[index, f'Channel {i}'] = (x_i - mins[i]) / (maxs[i] - mins[i]) 
        # so if i want to change the value of an element in row x and column y, i should use '.loc[x, y]'

normalized.head()

,Channel 0,Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7
0,0.398048,0.556655,0.651273,0.904117,0.962742,0.958991,0.949470,0.924319
1,0.341273,0.451636,0.720235,0.939308,0.982591,0.982883,0.975530,0.964649
2,0.405614,0.555319,0.727455,0.956913,0.982049,0.981164,0.973280,0.961682
3,0.455341,0.642354,0.674856,0.926043,0.966635,0.962692,0.953919,0.931323
4,0.416698,0.582189,0.649276,0.901790,0.961160,0.957521,0.947033,0.921056

Great! We have a new DataFrame of the normalized values.

## Final Notes

Thank you for reading through my first blog. I have been programming for about 5 years but I am new to documenting my thought process
<br>
in every step I make. I feel doing this has helped me create a good foundation in Pandas because instead of doing a quick look up whenever
<br>
I need a specific function for a task, I can learn it all step by step so when the time comes, I know how to do it on my own.
<br>

Today we covered:
- Isolating specific rows and columns
- Indexing rows and columns
- Functions for describing data (min, max, average)
- Sorting data
- Filtering data (multi-conditional)
- Creating new DataFrames from existing data
- Normalization (min-max method)

## Next time: EEG Data Visualization

Now that I have this data sorted and normalized, I think it would be a good idea to visualize it with matplotlib, or maybe something else.
<br>
Most likely, I will explore different methods for plotting this multi-dimensional time-series data. And I hope to replicate some of the visuals
<br>
I have seen in EEG research papers.


For the future, this entire blog will not be completely linear. Since my 5-channel Emotiv _Insight_ headset is on its way, I will also be making 
<br>
some blogs in which I use the API to code a BCI that allows me do perform some sorts of functions through my own thoughts.
<br>

Since I will not have access to the Raw-EEG data (at least not yet), I cannot do too much signal processing, but my plan is to build these signal processing
<br>
skills using sample datasets from various sources, and by the time I can read in my own Raw-EEG data, I will be skilled enough to process and visualize it.

Thank for reading and see you next time!
<br>
-James McAleer