# Reading and Sorting EEG data with Pandas
Hi my name is James and I'm a CS student at Binghamton University.
<br>
The goal of this entire ML and BCI blog is to build a strong foundation in statistics, machine learning, and signal processing so that I can apply it to brain-computer-interface (BCI) research.

BCI's are my #1 interest so instead of rushing into state-of-the-art research and trying to learn about CNN's and other deep learning things right away (as I have tried to the past week), I thought I should be discipline and start from the beginning.

Today I will be learning about Pandas
- I've worked with Pandas before, but it was more to use it for a piece of a project, so I never took the time to actually _learn_ it fully.
- Pandas will be crucial to the following blogs because I will be working with data for the rest of the existence of this blog.
- I plan to learn as much as I can throughout this notebook!

_Please_ email me if you have any questions or see any mistakes in either my code or commentary (jamesmcaleer717@gmail.com)

In [12]:
pip install pandas

Requirement already satisfied: pandas in /opt/homebrew/Cellar/jupyterlab/4.3.3/libexec/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/Cellar/jupyterlab/4.3.3/libexec/lib/python3.13/site-packages (from pandas) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/Cellar/jupyterlab/4.3.3/libexec/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/Cellar/jupyterlab/4.3.3/libexec/lib/python3.13/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/Cellar/jupyterlab/4.3.3/libexec/lib/python3.13/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /opt/homebrew/Cellar/jupyterlab/4.3.3/libexec/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [13]:
import pandas as pd

I will be inserting and plotting data from OpenBCI's sample data that comes with their GUI applications
<br>

"It's a text file, so although I use the read_csv function, I have to specify tab (\t) as the delimiter"
<br>

I am going to keep this blog transparent, this above was my thought at first but as I looked further into the data, I realized it _was_ still comma separated
<br>
I also had issues trying to show the columns due to the incorrect parsing of information due to the '%' signs as comments in the txt file
<br>
I now know to include the comment argument when reading a file

In [31]:
df = pd.read_csv('/Users/jmac/Programming/BCI/2025/blog/notebooks/pandas/openbci-sample.txt', delimiter=',', comment='%')

So here is the columns of the data!
<br>
Everything is stored in something called a pandas _DataFrame_ which is the object that holds this table of rows and columns

In [32]:
print(df.columns)

Index(['Sample Index', ' EXG Channel 0', ' EXG Channel 1', ' EXG Channel 2',
       ' EXG Channel 3', ' EXG Channel 4', ' EXG Channel 5', ' EXG Channel 6',
       ' EXG Channel 7', ' Accel Channel 0', ' Accel Channel 1',
       ' Accel Channel 2', ' Not Used', ' Digital Channel 0 (D11)',
       ' Digital Channel 1 (D12)', ' Digital Channel 2 (D13)',
       ' Digital Channel 3 (D17)', ' Not Used.1', ' Digital Channel 4 (D18)',
       ' Analog Channel 0', ' Analog Channel 1', ' Analog Channel 2',
       ' Timestamp', ' Marker Channel', ' Timestamp (Formatted)'],
      dtype='object')

And here is an example of one of the samples

In [44]:
print(df.head(1))

   Sample Index   EXG Channel 0   EXG Channel 1   EXG Channel 2  \
0             0        61379.36        49492.89       -16597.06

    EXG Channel 3   EXG Channel 4   EXG Channel 5   EXG Channel 6  \
0       -21309.75         6703.91        -3284.86          7223.1

    EXG Channel 7   Accel Channel 0  ...   Digital Channel 2 (D13)  \
0         1740.11              0.04  ...                         0

    Digital Channel 3 (D17)   Not Used.1   Digital Channel 4 (D18)  \
0                         0            0                         0

    Analog Channel 0   Analog Channel 1   Analog Channel 2      Timestamp  \
0                  0                  0                  0  1557936053329

    Marker Channel   Timestamp (Formatted)
0                0            12:00:53.329

[1 rows x 25 columns]

You can see as I increase the value inside of .head(), we have more samples. This is good to know

In [45]:
print(df.head(5))

   Sample Index   EXG Channel 0   EXG Channel 1   EXG Channel 2  \
0             0        61379.36        49492.89       -16597.06
1             1        60973.46        48972.47       -16279.02
2             2        61433.45        49486.27       -16245.72
3             3        61788.96        49917.57       -16488.30
4             4        61512.69        49619.42       -16606.27

    EXG Channel 3   EXG Channel 4   EXG Channel 5   EXG Channel 6  \
0       -21309.75         6703.91        -3284.86         7223.10
1       -21050.13         7045.02        -2887.53         7593.09
2       -20920.25         7035.70        -2916.12         7561.15
3       -21147.99         6770.81        -3223.32         7286.27
4       -21326.92         6676.73        -3309.31         7188.50

    EXG Channel 7   Accel Channel 0  ...   Digital Channel 2 (D13)  \
0         1740.11              0.04  ...                         0
1         2118.70              0.04  ...                         0
2         2090.85              0.04  ...                         0
3         1805.86              0.04  ...                         0
4         1709.48              0.04  ...                         0

    Digital Channel 3 (D17)   Not Used.1   Digital Channel 4 (D18)  \
0                         0            0                         0
1                         0            0                         0
2                         0            0                         0
3                         0            0                         0
4                         0            0                         0

    Analog Channel 0   Analog Channel 1   Analog Channel 2      Timestamp  \
0                  0                  0                  0  1557936053329
1                  0                  0                  0  1557936053336
2                  0                  0                  0  1557936053336
3                  0                  0                  0  1557936053343
4                  0                  0                  0  1557936053343

    Marker Channel   Timestamp (Formatted)
0                0            12:00:53.329
1                0            12:00:53.336
2                0            12:00:53.336
3                0            12:00:53.343
4                0            12:00:53.343

[5 rows x 25 columns]

And here are the first 20 samples from Channel 0
<br>

I've also noticed that while 'EXG' channels have data, 'Digital' channels do not, so from here on out, I will only be displaying information from 'EXG' channels

In [49]:
print(df[' EXG Channel 0'][0:20])

0     61379.36
1     60973.46
2     61433.45
3     61788.96
4     61512.69
5     60988.50
6     61315.06
7     61769.25
8     61622.57
9     61061.59
10    61240.47
11    61796.87
12    61744.46
13    61160.23
14    61165.82
15    61760.48
16    61824.21
17    61294.61
18    61103.03
19    61696.47
Name:  EXG Channel 0, dtype: float64

Now to show multiple columns, we put the column names in a list. Now if you think im going to type out all 8 channels in brute-force, you don't know me yet.

In [50]:
print(df[ [' EXG Channel 0', ' EXG Channel 1'] ]) # .. and so on

       EXG Channel 0  EXG Channel 1  EXG Channel 2
0           61379.36       49492.89      -16597.06
1           60973.46       48972.47      -16279.02
2           61433.45       49486.27      -16245.72
3           61788.96       49917.57      -16488.30
4           61512.69       49619.42      -16606.27
...              ...            ...            ...
22485       58750.42       47034.95      -18637.04
22486       59029.14       47391.53      -18737.73
22487       58890.72       47196.80      -18850.75
22488       58567.63       46769.70      -18777.12
22489       58705.56       46972.84      -18624.12

[22490 rows x 3 columns]

Let's come up with a better solution...
<br>
And great, it works!

In [52]:
chans = []
for i in range(8):
    chans.append(f" EXG Channel {i}")

print(df[chans])

       EXG Channel 0  EXG Channel 1  EXG Channel 2  EXG Channel 3  \
0           61379.36       49492.89      -16597.06      -21309.75
1           60973.46       48972.47      -16279.02      -21050.13
2           61433.45       49486.27      -16245.72      -20920.25
3           61788.96       49917.57      -16488.30      -21147.99
4           61512.69       49619.42      -16606.27      -21326.92
...              ...            ...            ...            ...
22485       58750.42       47034.95      -18637.04      -27128.40
22486       59029.14       47391.53      -18737.73      -27217.09
22487       58890.72       47196.80      -18850.75      -27389.65
22488       58567.63       46769.70      -18777.12      -27361.26
22489       58705.56       46972.84      -18624.12      -27123.57

       EXG Channel 4  EXG Channel 5  EXG Channel 6  EXG Channel 7
0            6703.91       -3284.86        7223.10        1740.11
1            7045.02       -2887.53        7593.09        2118.70
2            7035.70       -2916.12        7561.15        2090.85
3            6770.81       -3223.32        7286.27        1805.86
4            6676.73       -3309.31        7188.50        1709.48
...              ...            ...            ...            ...
22485       -9182.90      -18376.35       -5918.16       -6498.79
22486       -9327.85      -18544.50       -6069.39       -6654.94
22487       -9400.32      -18621.62       -6141.32       -6739.32
22488       -9255.01      -18427.36       -5976.43       -6570.79
22489       -9153.87      -18340.03       -5887.83       -6470.99

[22490 rows x 8 columns]

'iloc' allows me to get specific rows from the DataFrame

In [56]:
df.iloc[0:2]

,Sample Index,EXG Channel 0,EXG Channel 1,EXG Channel 2,EXG Channel 3,EXG Channel 4,EXG Channel 5,EXG Channel 6,EXG Channel 7,Accel Channel 0,...,Digital Channel 2 (D13),Digital Channel 3 (D17),Not Used.1,Digital Channel 4 (D18),Analog Channel 0,Analog Channel 1,Analog Channel 2,Timestamp,Marker Channel,Timestamp (Formatted)
0,0,61379.36,49492.89,-16597.06,-21309.75,6703.91,-3284.86,7223.10,1740.11,0.04,...,0,0,0,0,0,0,0,1557936053329,0,12:00:53.329
1,1,60973.46,48972.47,-16279.02,-21050.13,7045.02,-2887.53,7593.09,2118.70,0.04,...,0,0,0,0,0,0,0,1557936053336,0,12:00:53.336

Let's combine this with getting retrieving specific columns to get a chunk of the EEG data I'm looking for...

In [57]:
df[chans].iloc[0:10]

,EXG Channel 0,EXG Channel 1,EXG Channel 2,EXG Channel 3,EXG Channel 4,EXG Channel 5,EXG Channel 6,EXG Channel 7
0,61379.36,49492.89,-16597.06,-21309.75,6703.91,-3284.86,7223.10,1740.11
1,60973.46,48972.47,-16279.02,-21050.13,7045.02,-2887.53,7593.09,2118.70
2,61433.45,49486.27,-16245.72,-20920.25,7035.70,-2916.12,7561.15,2090.85
3,61788.96,49917.57,-16488.30,-21147.99,6770.81,-3223.32,7286.27,1805.86
4,61512.69,49619.42,-16606.27,-21326.92,6676.73,-3309.31,7188.50,1709.48
5,60988.50,48976.52,-16344.53,-21154.36,6952.42,-2958.16,7481.04,2029.85
6,61315.06,49330.77,-16228.46,-20954.00,7035.21,-2914.51,7554.31,2106.12
7,61769.25,49873.18,-16460.85,-21159.12,6771.26,-3225.07,7291.07,1823.68
8,61622.57,49717.79,-16574.18,-21321.87,6670.45,-3319.14,7204.59,1729.71
9,61061.59,49044.09,-16355.02,-21197.70,6914.80,-2998.60,7478.65,2022.79

Now I'm going to try a couple of options for iterating through this data, sample-by-sample

In [72]:
two_chans = chans[0:2]

for i in range(3):
    print(df[two_chans].iloc[i]) # only showing the first 2 channels and first 3 samples to save space

EXG Channel 0    61379.36
EXG Channel 1    49492.89
Name: 0, dtype: float64
EXG Channel 0    60973.46
EXG Channel 1    48972.47
Name: 1, dtype: float64
EXG Channel 0    61433.45
EXG Channel 1    49486.27
Name: 2, dtype: float64

This pre-built function I found 'iterrows()' seems to have the same effect
<br>

I don't seem to have the same control over how many rows I iterate through, and I would imagine iterrows() is faster than me calling iloc() every iteration
<br>

So from here on out, I will be using the pre-built function
<br>

If I don't want to loop through ALL samples, I simply call iloc() once on the dataframe before the loop to chop it

In [83]:
for index, row in df[two_chans].iloc[0:3].iterrows():
    print(f"Sample: {index}", row)

Sample: 0 EXG Channel 0    61379.36
EXG Channel 1    49492.89
Name: 0, dtype: float64
Sample: 1 EXG Channel 0    60973.46
EXG Channel 1    48972.47
Name: 1, dtype: float64
Sample: 2 EXG Channel 0    61433.45
EXG Channel 1    49486.27
Name: 2, dtype: float64

Now that I have some control over this data, I want to start looking for peaks, averages, and more
<br>

To start with this, let's explore the 'loc()' function, not to be confused wit 'iloc()'
<br>

To my knowledge, 'loc()' lets me find parts of the DataFrame where a condition is true, similar to the 'WHERE' in SQL
<br>

I'm going to try to show rows where the amplitude is above average in Channel 0
<br>

<hr>

So something weird happened here, when I tried to call 'iterrows()' on df[' EXG Channel 0'], I had an error as I could not call the method on a Series
<br>
Instead, I have to nest the channel in another list, similar to my list 'chans' before so that the type is correct to run the method on

<hr>

Anyways, it was a success. From a programming standpoint, if you are wondering how I used 'index' for calculating my average, the last value of 'index' (and any other incrementing value) retains its final value and can be used outside the loop. Pretty cool

In [102]:
sum_vals = 0
for index, row in df[ [' EXG Channel 0'] ].iterrows():
    sum_vals += row[' EXG Channel 0']

avg = sum_vals / index

df.loc[df[' EXG Channel 0'] > avg][chans]

,EXG Channel 0,EXG Channel 1,EXG Channel 2,EXG Channel 3,EXG Channel 4,EXG Channel 5,EXG Channel 6,EXG Channel 7
49,62115.68,49995.62,-16410.43,-21149.15,6761.22,-3218.14,7325.83,1857.05
53,62131.95,49988.42,-16366.66,-21125.55,6796.81,-3184.70,7363.18,1905.26
57,62141.63,49966.92,-16335.53,-21079.88,6825.46,-3134.47,7412.31,1949.30
61,62087.18,49875.99,-16326.41,-21072.31,6832.50,-3141.14,7410.81,1938.68
62,62103.98,49894.99,-16482.42,-21258.61,6691.51,-3292.43,7265.05,1787.71
...,...,...,...,...,...,...,...,...
11762,62063.10,50175.29,-17061.58,-25087.46,-3624.87,-14380.49,-1304.47,-4666.73
11800,62075.04,50143.72,-17040.14,-25119.25,-3589.33,-14337.21,-1267.41,-4643.98
11804,62062.50,50147.81,-17079.24,-25141.35,-3647.04,-14393.79,-1315.40,-4686.40
11812,62064.18,50178.52,-17071.19,-25113.93,-3662.58,-14425.35,-1353.49,-4719.53
11829,62056.84,50148.71,-17090.08,-25149.33,-3677.26,-14415.58,-1349.84,-4702.76